name: Update Surf Forecast

on:
  schedule:
    - cron: '0 */6 * * *'    # every 6 hours
  workflow_dispatch:

permissions:
  contents: write     # give the GITHUB_TOKEN push rights
  id-token: write     # not strictly needed here but ok

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout using the built-in GITHUB_TOKEN with write access
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Install deps & run script
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate forecast pages
        run: |
          python surf_forecast.py

      # 4. Commit & push the updated HTML
      - name: Commit and push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/*.html
          git commit -m "Auto update surf forecast data" || echo "Nothing to commit"
          git push

      # 7) Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
