name: Update Surf Forecast

on:
  schedule:
    - cron: '0 */6 * * *'    # every 6 hours
  workflow_dispatch:

# Top-level permissions to allow the deploy-pages action to mint an OIDC token
permissions:
  contents: read     # for checkout
  pages: write       # to publish to GitHub Pages
  id-token: write    # required by configure-pages & deploy-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3) Install dependencies
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      # 4) Run your forecast script (writes into docs/)
      - name: Generate Surf Forecast pages
        run: |
          python surf_forecast.py

      # 5) Configure Pages
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      # 6) Upload everything in docs/ as the Pages artifact
      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs

      # 7) Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
