name: Update Surf Forecast

on:
  schedule:
    - cron: '0 */6 * * *'  # every 6h
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read     # for checkout
      pages: write       # to push to GitHub Pages
      id-token: write    # for deploy action

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate forecast pages
        run: python surf_forecast.py

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
